### ISSUE TITLE
[공통] 앱 내부에 Localization 도입 (다국어 지원)

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#103]
# 🚀 기능
앱에 영어와 한국어를 호환하는 로컬라이제이션(Localization) 기능을 추가합니다.
<br/>

## 📄 기능 명세
- [ ] Localization 패키지 도입 여부 논의
- [ ] Localization 기본 모듈 구축 예: AppLocalizationText, AppText
- [ ] Localization 모듈 로직 적용

<br/>

## 👷 작업자
@yundal8755 , @Yellowtoast, @Xim-ya  

<br/>

## 💬 기타
먼저 각자 간단한 보일러플레이트 프로젝트를 만들어 다국어 처리 기능 로직을 적용해봐도 좋을 것 같아요. 

Localization은 고려해야 할 부분이 많고 하드코딩 작업이 많아서 피로도가 높지만, 초반에 잘 만들어 놓으면 매우 유용할 것 같습니다.
보통 Localization을 적용할 때 여러 패키지를 도입하는데, 관련해서 각자 리서치를 해보면 좋을 것 같습니다.
제가 이전에 리서치한 패키지는 아래와 같습니다.

- <a href="https://pub.dev/packages/slang">slang<a/>
- <a href="https://fluttergems.dev/packages/easy_localization/">easy_localization<a/>

참고로, 제가 이전 프로젝트에 Localization을 적용했을 때 아래 블로그에서 마지막으로 제시하는 방법을 사용했습니다.
 <a href="https://jay-flow.medium.com/flutter-localizations-%EC%99%84%EC%A0%84-%EC%A0%95%EB%B3%B5-%ED%95%98%EA%B8%B0-8fa5f50a3fd2">[Flutter] Localizations 완전 정복 하기<a/>
 
 잘 정리되어 있으니 참고하시면 좋을 것 같아요!

**Comment by yundal8755** [comment]
<요약>
- Localization 패키지 도입: `easy_localization` 추천
    - 다른 패키지에 비해 설정이 간편하다
    - JSON을 활용해 직관적으로 사용이 가능하다
- 패키지 기본 모듈 구축
    - `easy_localization`으로 boilerplate 제작
    - `AppLocaleText`: 하드코딩으로 변수 선언

자세한 내용은 하단의 노션 링크 참고해주세요!
https://www.notion.so/1-c3d1df54a62f46109b5f4a728290e851?pvs=21

**Comment by Yellowtoast** [comment]
<p><strong>flutter_localization + intl</strong></p>
<ul>
<li>context를 통과시키지 않아도 됨</li>
<li>아래와 같이 여전히 key값이 필요는 함</li>
<li>build 과정이 복잡함</li>
</ul>
<pre><code class="language-dart">import 'package:intl/intl.dart';
Text(Intl.message('appName'))
</code></pre>
<p><strong>easy_localization</strong></p>
<ul>
<li>context를 통과시켜야 적용됨</li>
<li>key값이 필요함</li>
<li>단순함</li>
</ul>
<p><strong>easy_localization 선택 이유</strong></p>
<ol>
<li>단순하게 사용할 수 있는 플러그인으로 빠르게</li>
<li>적용하기 쉬워야 함</li>
<li>자동 제너레이션 기능을 통해 text가 추가될때마다 휴먼에러 줄일 수 있음</li>
</ol>
<p><strong>키값 자동 제너레이션 방법</strong></p>
<h3>Command line arguments</h3>

Arguments | Short | Default | Description
-- | -- | -- | --
--help | -h |   | Help info
--source-dir | -S | resources/langs | Folder containing localization files
--source-file | -s | First file | File to use for localization
--output-dir | -O | lib/generated | Output folder stores for the generated file
--output-file | -o | codegen_loader.g.dart | Output file name
--format | -f | json | Support json or keys formats
--[no-]skip-unnecessary-keys | -u | false | Ignores keys defining nested object except for pluarl(), gender() keywords.


<p>키값 자동 제너레이션 방법</p>
<ol>
<li>
<p>json 형태로 json 파일 내부에 localization 텍스트 선언</p>
<p><img src="https://prod-files-secure.s3.us-west-2.amazonaws.com/af533a0d-a02c-46c7-81ca-9da13ee599e1/f4143734-16e6-4518-8da3-b9a15b3b5f82/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2024-07-14_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_4.15.56.png" alt="스크린샷 2024-07-14 오후 4.15.56.png"></p>
</li>
<li>
<p>키값 dart 파일의 생성을 원하는 폴더와, json 파일이 있는 폴더 경로를 사용하여 자동 코드 생성 명령어 입력<br>
<code>flutter pub run easy_localization:generate -O lib/app/localization -f keys -o locale_keys.g.dart --source-dir ./assets/translations</code></p>
</li>
</ol>

**Comment by Xim-ya** [comment]
## 정리

1. Easy Localization 패키지를 이용하여 en ko 다국어 지원 기능 도입
- 각 en ko json 파일의 json key값이 서로 다르거나 누락되는 경우 오류가 발생. 즉 휴먼에러 발생 위험이 높음. 관련해서 각 json 파일의 싱크를 어떻게 맞출 수 있을지에 대한 고민이 필요

2. Db Localization 구조로 변환
- @yundal8755 윤수님이 제안해주신 구조로 변환 완료.
- Firestore API READ 횟수를 최소화하고 기존 운영앱에 영향을 미치지 않은 범위내에서 DB 구조를 성공적으로 변경함.
