### ISSUE TITLE
[공통] Firstore Database Localization 

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#104]
# 🚀 기능
Localization 도입을 위해 데이터베이스 다국어 처리 작업을 진행합니다. 현재 Firestore에는 한국어 버전의 면접 질문과 답변 데이터만 존재합니다. 앱을 사용하는 사용자의 지역에 따라 DB에서 영어 버전의 데이터도 호출할 수 있어야 합니다.

<br/>

## 📸 상세
> 이 작업은 크게 두 부분으로 나뉩니다:
> - 데이터베이스에 영어 버전의 질문과 답변 데이터셋을 추가하는 작업
> - 앱에서 선택된 지역에 따라 조건별로 적절한 언어의 질문과 답변 데이터를 호출하는 작업

### 현재 Firestore Collection Document 구조
![kore](https://github.com/MakeFrog/TechTalk/assets/75591730/fe1e14aa-102e-46eb-b529-49308924c128)

### Localization 대응 Firestore Collection Document 구조 (예시)
![eng](https://github.com/MakeFrog/TechTalk/assets/75591730/562cbbe3-f8f0-4eca-a79b-9f5b4818a640)
DB 구조를 변경한다면 위와 같이 개선할 수 있을 것 같습니다.

<br/>

## 📄 기능 명세
- [ ] 모범 답변 & 질문 데이터셋을 가지고 있는 Firestore 'Topic' Collection의 Collection/Document 구조 변경
- [ ] 영어 버전의 모범 답변 & 질문 데이터셋을 DB에 저장
- [ ] 앱에서 선택된 지역에 따라 조건별로 특정 언어의 모범 답변과 질문들을 호출하는 로직 적용

<br/>

## 👷 작업자
@yundal8755 
@Yellowtoast 

## 💬 기타
없음

**Comment by Yellowtoast** [comment]
Locale에 들어가는 language code나 country code는 아무 형태의 스트링이 들어갈 수 있어서, firebase collection에 접근할 경우에는 저희가 한번 정제하여 가능한 language code로만 들어갈 수 있도록 예외 처리가 필요할 것 같습니다!

이러한 예외처리를 위해 기존에 선언된 Localization enum 값과 비교하여 매핑하는 방법도 있겠으나, 해당 방법은 추후에 앱 업데이트 없이 언어를 추가하는 것이 불가능한 문제가 있습니다.😢

따라서 아예 저희 db에 지원하는 locale 관련 정보를 넣어놓고, 사용하면 어떨까 제안드려봅니다! 

이 방식을 통해 앱에 static하게 정의되어있는 언어의 경우 업데이트가 필요하겠지만, 면접질문과 같이 db를 통해 가져오는 데이터의 경우에는 새로운 언어 추가가 자유롭게 이루어질 수 있을 것 같습니다.
