### ISSUE TITLE
[공통] Gemini AI 프롬프트에서 욕설 및 적절치 않은 언어 필터링

### ISSUE THREAD

**Issue by Yellowtoast** [MakeFrog/TechTalk#112]
# 🚀 기능

**문제**
- 사용자가 적절치 못한 응답을 제공하였을 때 (ex. 욕설 및 비속어) Gemini의 Safety Setting 값을 제공하지 않으면 예상치 못한 오류가 발생하는 문제가 있습니다. 
- Safety Setting을 설정하지 않았을 경우 Gemini에서 적절한 응답값을 보내주지 못하는 현상 해결이 필요합니다.
- OpenAI와 달리 Stream 값으로 넘어올 때 텍스트들이 분리되어 넘어오므로, 관련 예외 처리가 필요함

**해결**
Safety Setting을 none으로 설정하되, 부적절한 응답값의 경우 다른 태그값을 붙이도록 하여 대응하고자 합니다.

## 📸 재현 이미지 또는 코드 샘플

![스크린샷 2024-07-29 오후 3 04 27](https://github.com/user-attachments/assets/6417b3f8-3478-42f4-88c9-4d31c23ccd0b)
![스크린샷 2024-07-29 오후 3 04 45](https://github.com/user-attachments/assets/f76c6523-a919-41ff-9c5d-190236c52e95)

## 📄 기능 명세

1. Gemini의 SafetySettings를 none으로 설정
2. 프롬프팅에서 적절하지 않은 유저응답일 경우 [i] 태그를 붙이도록 수정
3. checkAnswer 콜백 함수에서 isCorrect이 아닌 AnswerState 값을 리턴하여 대응할 수 있도록 변경
  - 추후 응답 상태가 고도화 되었을 때 이에 맞게 UI에서 반영하기 위함 

## 👷 작업자

@Yellowtoast , @Xim-ya

**Comment by Xim-ya** [comment]
## 정리

- Chat GPT에서 Gemini 생성형 모델 마이그레이션을 성공적으로 진행.
- Chat GPT 모델과 비교했을 때 응답 퀄리티 및 성능적인 부분에서 큰 차이가 없음.
- 다만 다양한 생성형 언어 모델을 사용한 기능 확장이 유리한 여부와 API 사용 부하적인 부분에서 큰 문제가 없는지는 지속적인 고민이 필요.
- 아직 더 프롬프트를 고도화 해봐야겠지만, prompt에 요구사항을 많이 추가할수록 응답 정확도가 떨어지는 부분이 존재했음. 관련 부분해서는 조금 더 고민이 필요.
