### ISSUE TITLE
[채팅면접] 답변에 따른 점수 판별 프롬프트 로직 추가 / 프롬프트 응답 형태 변경

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#117]
# 🚀 기능

AI모델이 사용자의 답변을 평가할 때 0~5 사이의 점수를 매길 수 있도록 프롬프트 코드를 수정합니다. 참고로, 점수 기준은 정해진 것이 없으므로 모델이 자체적으로 판단하거나 저희가 대략적으로 정할 수 있습니다.

또한 응답 형태를 String에서 JSON으로 변경합니다.

## 📄 기능 명세

- [ ] ChatGPT 4.0 모델을 사용.
- [ ] 사용자의 답변 완성도에 따라 0~5 사이의 점수를 매김.
- [ ] AI 모델의 응답 형태를 String에서 JSON으로 변경.
- [ ] 점수에 따라 정답 여부를 판단하며, 정답으로 판별되는 점수 범위는 유동적으로 변경될 수 있도록 프롬프트 코드를 수정함.

예) 2점 이상 정답 판별 → 3점 이상 정답 판별로 변경

## 👷 작업자
@Yellowtoast 

## 💬 기타
답변의 완성도에 따라 ai 모델이 점수를 어떻게 판별하는지 정리하여 금주 회의 때 공유드려야 합니다.

**Comment by Yellowtoast** [comment]
# 🚀 확정된 구현 기능

AI 모델은 사용자의 답변에 대해 피드백을 제공함. 그 다음 사용자의 답변 완성도에 대하여 0~5점 사이의 점수를 매기고, 답변의 퀄리티에 따라 꼬리질문 및 꼬리질문이 제공된 이유를 제공할 수 있도록 프롬프트 수정

[240907 확정 내용]
사용자에 답변에 대한 피드백, 점수, 꼬리질문 필요 여부만 제공받은 후에, 꼬리질문 필요 여부에 따라 별도의 usecase에서 꼬리질문을 생성하는 방식으로 진행하겠습니다.


## 📄 기능 명세

- [ ] ChatGPT 4.0 모델을 사용.
- [ ] AI 모델이 피드백 및 점수, 꼬리질문 필요 여부 데이터를 제공할 수 있도록 프롬프트 코드 수정
- [ ] AI 모델이 꼬리질문을 생성할 수 있도록 새로운 기능 구현
- [ ] AI 모델의 응답 형태 일부 String, 일부 JSON으로 리턴받을 수 있도록 수정

## 👷 작업자
@Yellowtoast
