### ISSUE TITLE
[면접] 꼬리질문 기능 구현 테크스펙

### ISSUE THREAD

**Issue by Yellowtoast** [MakeFrog/TechTalk#123]
# 꼬리질문 개발 테크스펙

## **요약 (Summary)**

메인 질문에 대한 유저의 답변을 기반으로 꼬리질문이 필요한 경우 꼬리질문을 프롬프트로 생성하여 진행합니다. 

## **배경 (Background)**

유저의 답변을 기반으로 꼬리질문을 제공하여 유저가 추가적으로 습득하고 공부해야 할 방향성을 파악할 수 있습니다. 
이를 통해 면접기능의 퀄리티를 향상시키고 유저에게 보다 최적화된 면접 기능을 제공하고자 합니다.

## **목표 (Goals)**

1. 꼬리질문 기능을 면접방 상단 토글 버튼을 이용하여 꺼거나 켤 수 있도록 한다.
2. 메인 질문에 대한 유저의 답변을 기반으로 꼬리질문을 프롬프트로 생성하여 제공한다.  
3. 메인 질문 하나당 1개 이상의 꼬리질문이 제공될 수 있다. - 현재는 1개까지만 제공
4. 메인 질문과 관련있는 꼬리질문과 꼬리질문 생성 이유를 문답 탭에서 확인할 수 있도록 한다.

## **계획 (Plan)**

- 메인질문과 관련 대화의 context를 기반으로 꼬리질문 프롬프트를 생성해야 함.
- 메인질문 하나당 1개 이상의 꼬리질문이 생성될 수 있어야 함.
    - 메인질문과 꼬리질문을 구분하고, 포함관계를 설정해야 함
- 기존 피드백 use case 를 꼬리질문에 대해서도 사용할 수 있어야 함.

### **메인질문 및 꼬리질문 제공 로직**

```mermaid
flowchart TD
    A0[시작] --> A1[변수 선언 및 데이터 준비]
    A1 --> A2[SetAiFeedbackUseCase 호출]
    A2 --> B1{응답 수신}
    
    %% onSuccess 흐름
    B1 --> |성공| C1[피드백 채팅 메시지 표시]
    
    %% onFailure 흐름
    B1 --> |실패| D1[응답 롤백 및 오류 스낵바 표시]
    
    %% 콜백: checkAnswer
    A2 --> A3[checkAnswer 콜백]
    A3 --> A4{AnswerState 확인}
    A4 --> |error| A5[응답 롤백 및 오류 팝업 표시]
    A4 --> |정상| A6[resolvedUserAnswer 업데이트 및 isAnswerCorrect 설정]
    
    %% 콜백: onFeedBackCompleted
    A2 --> A7[onFeedBackCompleted 콜백]
    A7 --> A8[로깅 및 Firebase Analytics 이벤트 기록]
    A8 --> A9[FeedbackChatEntity 생성]
    A9 --> A10{꼬리 질문 필요 여부 및 조건 확인}
    A10 --> |예| A11[GuideChatEntity 생성 및 메시지 업로드]
    A11 --> A12[_startFollowUpQuestion 호출 및 종료]
    A10 --> |아니오| A13{마지막 질문 확인}
    A13 --> |아니오| A14[새로운 QnA 및 GuideMessage 생성]
    A13 --> |예| A15[인터뷰 종료 메시지 생성]
    A14 --> A16[GuideChatEntity 및 QuestionChatEntity 생성]
    A15 --> A16
    A16 --> A17[메시지 업로드 및 표시]
    
    %% 보조 함수 흐름
    A12 --> B2[_startFollowUpQuestion 실행]
    B2 --> B3[SetAiFollowUpQuestionUseCase 호출]
    B3 --> B4{스트림 응답 수신}
    B4 --> |성공| B5[꼬리 질문 메시지 표시]
    B4 --> |실패| B6[응답 롤백 및 오류 스낵바 표시]
    B5 --> |스트림 종료| B7[FollowUpQuestionChatEntity 반환 및 데이터 저장]
    B6 --> B7
```

### **간단한 Flow Chart **

![image](https://github.com/user-attachments/assets/a930cf40-d0e3-458d-a0e7-917fafa39d15)

> 채팅방의 상태는, 메세지가 ChatHistory에 추가될 때마다 listen하여 변경됩니다. 
> 꼬리질문이 진행되는 경우 4개중에 3번째 메인 질문에서 꼬리질문 로직이 수행되었을 때, 꼬리질문에 대한 피드백이 추가되었다고 하더라도 면접을 종료해서는 안되므로 아래의 코드를 추가하였습니다.

<img width="783" alt="스크린샷 2024-09-20 오후 7 26 49" src="https://github.com/user-attachments/assets/fda5fdec-bf5f-4b0d-9d4f-8d1b54e8f322">

### 1. 새로운 메인질문 제공
  **1-a. 방이 생성된 후 처음 제공하는 질문은 ChatMessageHistory에서 수행**
<img width="677" alt="스크린샷 2024-09-20 오후 7 06 29" src="https://github.com/user-attachments/assets/3d02677a-eebd-49c9-b6dd-17c08bc55208">
  **1-b. 그 다음 질문은 ChatMessageHistory 에서 수행됨**
- 해당 단계에서는 피드백 제공 후 곧바로 다음 질문 제공됨.

<img width="665" alt="스크린샷 2024-09-20 오후 7 05 08" src="https://github.com/user-attachments/assets/a0f98659-32db-4635-9361-4bea15df4e98">

### 2. 유저의 답변 추가

> 유저의 답변이 추가되는 동시에, 피드백 프롬프트 실행됨
> 피드백 채팅이 노출 된 후 아래의 로직대로 수행됩니다.

  **2-a. 꼬리질문이 필요할 경우**
- 꼬리질문 가이드 텍스트 노출
- 현재 질문에 대한 유저의 답변, 현재 질문에 대한 피드백, 꼬리질문 가이드 채팅 -> 3개의 데이터를 서버에 저장함
- 꼬리질문 use case를 실행하여 꼬리질문을 스트림 형태로 보여줌
- 꼬리질문 스트림이 완료되면, 꼬리질문 -> 1개의 데이터를 서버에 저장함
- 채팅방의 상태를 변화시킴, 단 오/정답 개수는 변화시키지 않음
- 리턴
<img width="662" alt="스크린샷 2024-09-20 오후 7 19 04" src="https://github.com/user-attachments/assets/2b4d72f6-2cd6-4081-929d-4e498b60cf9d">

  **2-b. 꼬리질문이 필요하지 않을 경우**
- 유저가 답변한 현재 질문에 대한 오/정답 여부 채팅방에 업데이트
- 다음 메인질문을 DB에서 가져옴
- 현재 질문에 대한 유저의 답변, 현재 질문에 대한 피드백, 가이드채팅, 다음 메인질문 -> 4개의 데이터를 서버에 저장함

### **메인질문과 꼬리질문 데이터 저장 형태**

- **메인질문** : `rootQnaId`와 `qnaId`가 동일하며, ‘flutter-1’ 과 같은 값으로 db에 저장되어 컨트롤된다.
- **꼬리질문** : `rootQnaId`는 메인질문의 `qnaId`가 되며, `qnaId`는 Uuid.v1()으로 생성된 유니크한 값이 들어간다.

`QuestionChatEntity`, `FeedbackChatEntity`, `AnswerChatEntity` 에 `qnaId`와 `rootQnaId`필드를 추가한다.

`rootQnaId`를 기반으로 프롬프트를 위한 채팅 히스토리를 추출하고, 메인질문과 꼬리질문을 구분하기 위함

```dart
class QuestionChatEntity extends BaseChatEntity {
  final String qnaId;

  QuestionChatEntity({
    super.id,
    required this.qnaId,
    required String rootQnaId,
    required super.message,
    super.isStreamApplied = true,
    DateTime? timestamp,
    ChatType? type,
  }) : super(
          type: type ?? ChatType.question,
          timestamp: timestamp ?? DateTime.now(),
          rootQnaId: rootQnaId,
        );
        
  /// 이하 코드...
}

```

```dart
abstract class BaseChatEntity {
  final String id; // ID
  final BehaviorSubject<String> message; // 채팅 메세지
  final ChatType type; // 채팅 타입
  final DateTime timestamp;
  bool isStreamApplied; // Stream 적용 여부
  final String? rootQnaId; // 메인 질문 Id

  BaseChatEntity({
    String? id,
    required this.message,
    required this.type,
    required this.isStreamApplied,
    required this.timestamp,
    this.rootQnaId,
  }) : id = id ?? const Uuid().v1();

  /// 이하 코드...
}

```

### **피드백 제공 use case**

1. 채팅 히스토리를 인자로 받아 피드백을 스트림으로 실시간으로 제공한다. 
3. 피드백 가장 끝에 json 형식으로 꼬리질문 필요 여부, 꼬리질문 생성 이유를 제공한다.

### **꼬리질문 제공 use case**

1. SetAiFollowUpQuestionUseCase 의 인자로 채팅 히스토리와 메인질문 entity를 받는다.
2. 채팅 히스토리를 기반으로 꼬리질문을 스트림으로 생성하여 제공한다.
3. 스트림이 끝난 뒤에, 제공된 꼬리질문을 QuestionChatEntity 형태로 생성하여 채팅 히스토리에 저장한다.

** 꼬리질문 제공시에는, 오/정답 여부는 판단하여 UI에 표출하지만, 면접방 전체의 상태에는 변화를 주지 않는다.**

# **이외 고려사항들 (Other Considerations)**

- 꼬리질문 개수를 서버에서 컨트롤 할 수 있도록 할지 여부 고려 필요

# **질문들 (Open Questions)**

- BaseChatEntity를 구현한 여러 ChatEntity를 sealed class로 변경하는 것은 어떨까요?
    - 상속이 아닌 구현으로 변경하면 어떨까요?
- 방의 상태에 꼬리질문이 영향을 미치지 않도록 함수 내부에 return 문을 넣었는데, 보다 효과적이고 재사용 가능하도록 컨트롤 할 수 있는 방법이 있을까요?
<img width="568" alt="스크린샷 2024-09-20 오후 7 00 51" src="https://github.com/user-attachments/assets/67ddab0c-4a71-4c0b-88a3-c97e93b99f20">

**Comment by Xim-ya** [comment]
와...
초기 로직이나 전체적인 구성에 관여했던 저조차도 시간이 지나 잊어버렸던 명세들을 정말 제대로 짚어주셨네요.
코드를 분석하고 파악하기 정말 정말 어려우셨을 텐데, 정리해 주셔서 정말 감사합니다.

정말 이해하기 쉽게 잘 정리해 주셨네요 👍👍👍👍👍 

특히 작성해주신 문서 범위를 기반을 예외 경우나 영향 범위를 쉽게 파악할 수 있었씁니다.

해당 면접 질문 응답-AI 피드백 "기존 로직" 관련해서는 개선할 부분이 많아 보이는데, 서비스의 가장 핵심 로직인 만큼 개선점을 천천히 찾아가 보면 좋을 것 같네요!
