### ISSUE TITLE
[공통] Data 상세 레이어 구조 논의

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#13]
# 🤝 논의사항
테크톡 프로젝트는 크게 `feature`(feature-first)중심의 `data-domain-presenation` 레이어로 구분되어있고,
data의 세부 레이어는 `dataSource` `repository`로 구성됩니다.

이때 `data 세부 레이어`의 구조와 폴더 구조에 대한 의견 차이가 있어서 논의를 진행합니다.

출처 : [PR Comment (레이어의 역할 구분)](https://github.com/MakeFrog/TechTalk/pull/11)
<br/>

## 📝 상세 내용

> @suneogkwon 

**폴더 구조**
```
- data
  - data_source
    - remote
    - local
    - model
  - repositories
    - repository
    - entity  
```
**구조 흐름**
<img width="1158" alt="diagram1" src="https://github.com/MakeFrog/TechTalk/assets/75591730/606984d2-1aa6-4c65-87ff-4833514fd62b">

- dataSource는 원격/로컬 여부에 따라 나누어집니다. ex) interview_remote_data_source, interview_local_data_source
- repository에서 나누어진 2개의 dataSource모듈을 참조하여 필요한 로직들을 실행합니다.
- repository에서는 다른 feature의 dataSource 모듈을 참조할 수 있습니다.

<br/>

> @Xim-ya 

**폴더 구조**
```
- data
  - data_source
    - a_data_source.dart
    - remote
    - local
    - model
  - repositories
    - entity   
```

**구조 흐름**
<img width="1353" alt="diagram2" src="https://github.com/MakeFrog/TechTalk/assets/75591730/3f7567d2-e51f-41a6-8cce-ed2eeb3f3af9">

- dataSource는 원격/로컬 여부에 따라 나누어집니다. 그리고 나누어진 각 모듈은 공통 data_source 모듈에서 주입받아 관리합니다. . ex) interview_data_source, interview_remote_data_source, interview_local_data_source 
- dataSource에서는 다른 feature의 dataSource 모듈을 참조할 수 있습니다.
- repository에서는 공통 dataSource 모듈을 주입받아 필요한 로직들을 실행합니다. (repository에서는 data_source의 내부 상세 구현 로직을 알 필요가 없습니다)

<br/>

## 🚀 기대 효과
- 레이어의 책임과 역할을 명확히 구분하여 더 유연하고 유지 보수가 가능한 구조로 개선합니다.

<br/>

## 👷 참가자
@suneogkwon , @Xim-ya 
<br/>

**Comment by suneogkwon** [comment]
https://github.com/MakeFrog/TechTalk/pull/11#discussion_r1385865262
레이어 안에서의 상호참조를 허용한다면 말씀하신대로 data source에서 다른 data source를 가져와 사용하는 것도 가능할 것 같습니다. 기능별로 분리를 하다보니 상호참조를 최대한 막으려했고 그러다보니 프레젠테이션 레이어의 vm에서 usecase를 통한 상호 연계 로직을 작성하려했습니다. 상호참조를 허용하는게 공수나 가독성면에서 더 좋긴한 것 같고 레이어별 폴더 구조에서도 상호참조는 허용하니 저희도 기능별로 디렉토리를 구분하되 상호참조를 허용하면 될 것 같습니다.

https://github.com/MakeFrog/TechTalk/pull/11#discussion_r1387475818
[플러터 프로젝트 구조에 대한 글](https://codewithandrea.com/articles/flutter-project-structure/)이 있어 공유드립니다.

기능별 폴더 구조를 채택했을 때 공유되는 entity, model 등을 위해 share 기능을 만드는 경우가 많다고 합니다.
글쓴이는 극단적으로 20개의 기능에서 2가지 기능에만 공유되는 경우에도 share에 넣는게 바람직한가라고 적어놨습니다.
글 마지막쯤에는 기능별로 나눠도 공유되는 상황을 피할 순없고 최대한 공유되는 부분을 적게, 균형있게 하라고 나와있습니다.

기능 사이에 공유가 필요할때 커플링을 최대한 낮춘다면 저는 잘못된 접근은 아니라 생각합니다.

**Comment by Xim-ya** [comment]
> 기능별 폴더 구조를 채택했을 때 공유되는 entity, model 등을 위해 share 기능을 만드는 경우가 많다고 합니다.
글쓴이는 극단적으로 20개의 기능에서 2가지 기능에만 공유되는 경우에도 share에 넣는게 바람직한가라고 적어놨습니다.
글 마지막쯤에는 기능별로 나눠도 공유되는 상황을 피할 순없고 최대한 공유되는 부분을 적게, 균형있게 하라고 나와있습니다.

네 저도 동의합니다!
share 섹션(기능)을 추가하여 2가지 이상의 기능에 공유되는 리소스들을 관리하는게 좋을 것 같네요.
리소스들의 영향 범위를 좀 더  명확하게 파악할 수 있을 것 같습니다.

```
- featureA
  - data
     - entities
  - repository
     - models   

- featureB
  - data
     - entities
  - repository
     - models  
     
- share
  - data
     - entities
  - repository
     - models         
 ```
 
 그럼, 폴더 구조는 위와 같이 구성는되는 걸까요?

**Comment by Xim-ya** [comment]
**공통 dataSource에 remote 과 local을 참조하게 하고,  repository 모듈은 단 하나의 dataSource 모듈만 참조하게 하는 구조**가 왜 적합하다고 생각하는지 저의 의견을 한번 설명드려 보겠습니다!

크게 2가지 이유가 있습니다.

### 1. 변경에 유연한 구조 (커플링 감소)
코드의 모듈 간 의존성을 최소화하고 변경에 유연한 구조를 유지하는 것이 중요합니다. 의존성이 높을수록 코드 변경이 어려워지기 때문입니다.


<img width="990" alt="스크린샷 2023-11-15 오전 2 38 16" src="https://github.com/MakeFrog/TechTalk/assets/75591730/f73c9836-6e6d-42f2-a3e7-8266248864ee">


예를 들어, repository는 동일한 기능의 remoteDataSource와 localDataSource를 참조하며, repository의 메소드는 조건에 따라 remote 또는 local에서 데이터를 가져오도록 되어 있습니다. (두 dataSource의 메소드는 동일한 타입의 데이터를 반환합니다)



<img width="917" alt="스크린샷 2023-11-15 오전 2 52 03" src="https://github.com/MakeFrog/TechTalk/assets/75591730/c61cf949-8040-4f8a-ac66-849a94983c5d">

만약 local 기능이 더 이상 필요하지 않다면, repository에서 두 곳을 수정해야 합니다.
 - localDataSource를 주입 받는 부분 제거
 -  a, b, c 메소드에서 localDataSource 관련 로직 제거.

<br/>

<img width="1236" alt="스크린샷 2023-11-15 오전 2 56 54" src="https://github.com/MakeFrog/TechTalk/assets/75591730/f0181d98-c139-437a-b3a7-bbec347fc2c0">

반면에, 공통 dataSource에 remote와 local을 참조하게 하고, repository 모듈은 단 하나의 dataSource 모듈만을 참조한다면, repository에서 수정할 부분이 없어집니다.


<img width="1163" alt="스크린샷 2023-11-15 오전 3 06 02" src="https://github.com/MakeFrog/TechTalk/assets/75591730/88a13fca-f886-45c2-b6ef-0f21b958ac99">


local 로직이 없어지더라도 repository가 참조하는 공통 dataSource는 동일한 데이터를 반환하기 때문입니다.

### 2. 레이어별 독립적인 테스트에 용이
공통 DataSource 구조는 레이어별로 독립적인 테스트를 수행하기에 더 용이한 구조입니다. repository 레이어만을 테스트한다고 가정해보겠습니다.

만약 repository가 참조하는 상위 dataSource 모듈이 많다면, 해당 모듈들에 대한 테스트 코드를 모두 작성해야 합니다. 하지만, 하나의 공통 dataSource만을 참조하는 repository라면 해당 dataSource에 대한 테스트 코드만 작성하면 되므로, 독립적인 레이어를 테스트하기가 더 간편해집니다.


이러한 이유에서 공통 dataSource 모듈에서 remote, local 모듈을 참조하는 구조가 적합하다고 생각합니다.

**Comment by suneogkwon** [comment]
https://github.com/MakeFrog/TechTalk/issues/13#issuecomment-1810571843 에 대한 제 의견이 잘못 전달 된 것 같습니다.
공유되는 기능이라도 일부에서만 공유되는 것이라면 share 디렉토리로 분리 하지 않고 기능끼리 참조하는 것이 어떻냐는 뜻입니다. 이렇게 하면 기능별 디렉토리를 적용하고 있는 상황에 기능 간 커플링이 일어날 수 있지만 공유가 일어난다고 모두 share에 넣어버리면 레이어별 디렉토리와 다를게 없을 것 같습니다.

**Comment by suneogkwon** [comment]
변경에 유연하고 독립적인 테스트가 가능한 구조에 대해서는 저도 공감합니다.

클린 아키텍처가 디렉토리 구조가 아닌 설계 개념이라 설계 원칙을 준수한다면 어떻게하든 괜찮다고 생각합니다.

[클린 아키텍처 레이어가 아닌 개념에 관한 글](https://medium.com/mj-studio/%ED%81%B4%EB%A6%B0%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EC%8D%BC%EB%8A%94%EB%8D%B0-%EC%99%9C-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EA%B0%80-%EB%8D%94-%EB%8D%94%EB%9F%AC%EC%9B%8C%EC%A7%80%EC%A7%80-3565aaffca8c)을 보시면 금방 이해하실 것 같습니다.

현 프로젝트 상황에서 data 레이어는 domain 레이어에 확실히 구분되어 있고, 의존성을 지키기에 data 레이어 내부적으로 어떻게 구현을 하고 디렉토리 구조를 짜고 하더라도 클린 아키텍처를 준수한다고 생각합니다.

해주님이 말씀하신 data source 집합체의 도입 여부에 대해서 궁금한 것이
1. `data source`가 `remote`와 `db`, `cache`의 데이터를 컨트롤한다면 `repository`는 단순 error 핸들링만 하는 것인가?
2. `repository`에서 `data source`를 참조해 사용하는 것보다 `use case`에서 `repository`를 참조해 사용하는 건 어떤가?

1번 의견은 과도한 추상화와 분리가 오히려 응집성을 깨지는 않을까라는 생각입니다. 데이터를 다루면서 에러 핸들링은 같은 곳에서 하는 것이 낫지 않을까 하는 개인적인 의견입니다. 하지만, 나눠서 가독성과 유지보수성이 향상된다면 전 말씀하신 방향에 찬성합니다.

2번 의견에 대한 예로 '로그인한 유저가 유저 데이터를 저장'하는 use case인 `saveUserDataUseCase`에서 `auth repo`로부터 인증 정보를 조회 후 인증되었다면 `user repo`를 통해 유저 데이터를 저정하는 플로우를 들 수 있을 것 같습니다. `use case`는 실제 행동을 나타내야하고 그 일련의 과정들은 `use case`에서 나누는 것은 어떤가라는 생각입니다.
