### ISSUE TITLE
[공통] 라우트 파라미터 전달 방식 논의

### ISSUE THREAD

**Issue by suneogkwon** [MakeFrog/TechTalk#15]
# 🤝 논의사항

provider 및 widget에서 라우트로부터 전달받은 파라미터 사용 방법 논의

<br/>

## 📝 상세 내용

* 기존 방식의 단점
  * 파라미터를 전달하기 위해 `notifier`에 정적 변수를 선언해야함
  * 여러 프로바이더에서 사용하기 어려움.

찾아보니 공식문서에서 [`family`와 `scope`를 설명](https://riverpod.dev/ko/docs/concepts/scopes)해주고 있고 이걸 사용하면 저희가 논의하는 주제의 답을 찾을 수 있을 것 같습니다.

공식문서를 참조해서 기존 코드를 변경해보면 

```dart
// lib/app/router/router.dart

  // 기존
  @override
  Widget build(BuildContext context, GoRouterState state) {
    final ChatPageRouteArg arg =
        (progressState: progressState, roomId: roomId, topic: topic);

    RouteArg.update(arg);
    return const ChatPage();
  }

  // 변경
  @override
  Widget build(BuildContext context, GoRouterState state) {
    final ChatPageRouteArg arg =
        (progressState: progressState, roomId: roomId, topic: topic);

    // RouteArg.update(arg);
    return ProviderScope(
      overrides: [
        chatPageRouteArgProvider.overrideWithValue(arg),
      ],
      child: const ChatPage(),
    );
  }
```

`RouteArg`를 변경하는 대신 `chatPageRouteArgProvider`를 만들어 프로바이더의 값을 override해주는 식으로 파라미터를 저장합니다.

```dart
// lib/presentation/pages/chat/providers/chat_page_route_arg_provider.dart

@riverpod
ChatPageRouteArg chatPageRouteArg(ChatPageRouteArgRef ref) {
  throw UnimplementedError;
}
```
`chatPageRouteArgProvider`는 위와 같이 초기값을 선언하지 않고, override 없이 사용할 때 에러를 리턴하도록 되어있습니다.

```dart
// lib/presentation/pages/chat/providers/chat_list_provider.dart

// 기존
@riverpod
class ChatList extends _$ChatList {
  @override
  FutureOr<List<ChatEntity>> build() async {
    //...
  }
}

// 변경
@Riverpod(
  dependencies: [
    chatPageRouteArg,
  ],
)
class ChatList extends _$ChatList {
  @override
  FutureOr<List<ChatEntity>> build() async {
    //...
  }
}
```

override한 `chatPageRouteArgProvider`를 사용하기 위해서는 사용하는 곳에서 `dependencies`를 선언해줘야합니다.

그러면 provider 내부에서 `final routeArg = ref.watch(chatPageRouteArgProvider);`를 통한 접근이 가능합니다.

<br/>

## 🚀 기대 효과

* 불필요한 RouteArg의 초기화 및 변경
* dependencies를 선언함으로서 해당 프로바이더에 사용되는 종속성을 확실히함.
* 공식문서 예제에 소개된 방법(https://github.com/rrousselGit/riverpod/blob/master/examples/marvel/lib/src/screens/home.dart)

<br/>

## 👷 참가자

@Xim-ya 
@suneogkwon 

<br/>

## 💬 기타

<br/>

**Comment by Xim-ya** [comment]
기존처럼 전역변수를 선언하여 Route Argument를 전달할 경우 `종속성`을 명확히 할 수 없다는 단점이 있는데,
이런 문제를 잘 보완한 해결책인것 같습니다! 

그리고 저희가 목표로 했던 메커니즘을 모두 만족하네요.
- `.family`를 사용하지 않고 provider에 Route Argument를 전달.
- 페이지 위젯에서 Route Argument을 전달 받지 않아야 함.
- 여러 provider에서 Route Argument에 값을 전달 받을 수 있어야 함. 

```dart
@riverpod
ChatPageRouteArg chatPageRouteArg(ChatPageRouteArgRef ref) {
  throw RouteExcpetion.routeArgumentNeeded();
}
```
나중에는 chatPageRouteArgProvider에서 Custom Exception을 리턴하도록 변경해도 좋을 것 같습니다!

**Comment by Xim-ya** [comment]
추가로 궁금한 게 있습니다!

흔한 경우는 아니지만,
라우팅해서 argument를 전달할 때 다른 페이지로 이동하는 것이 아니라,
`동일한 페이지`로 라우팅하여 `route stack이 쌓이는 경우`에는 라우팅 argument를 어떻게 `override`할 수 있나요?
(동일한 페이지로 라우트 할 때마다 전달하는 argument이 달라질 수 있습니다)

**Comment by suneogkwon** [comment]
> 추가로 궁금한 게 있습니다!
> 
> 흔한 경우는 아니지만, 라우팅해서 argument를 전달할 때 다른 페이지로 이동하는 것이 아니라, `동일한 페이지`로 라우팅하여 `route stack이 쌓이는 경우`에는 라우팅 argument를 어떻게 `override`할 수 있나요? (동일한 페이지로 라우트 할 때마다 전달하는 argument이 달라질 수 있습니다)

공식문서에 다음 글이 있습니다.

Remember that scopes introduce a new instance of the state of every provider that is overridden or has listed a dependency on a provider that was overridden. If you override with the same parameter in a different subtree of the app, it will not be the same instance of the provider's state. Families are more flexible in general, and with the upcoming code generation feature it is easy to use multiple parameters for a family. Often a good combination is to use both families and scoping. Use a family to provide general access to a piece of state anywhere in your app, and then use scoping to provide a specific instance of the family's state depending on where you are in the widget tree.

scope는 override에 선언된 프로바이더를 새로운 객체로 만든다고합니다. 같은 파라미터를 전달해도 만들어지는 객체는 별개라고 하네요.
해주님이 말씀하시는 같은 라우트를 새로운 페이지로 호출하는 경우에도 A페이지에서 만들어진 B라는 프로바이더와  A\`페이지에서 만들어지는 B`프로바이더랑은 별개라는 뜻 같습니다.

**Comment by Xim-ya** [comment]
오호.. 명쾌한 답변 감사합니다. 그럼 큰 문제가 없겠네요. 
이슈 닫고 이제부터 제시해 주신 방식으로 route argument을 전달하도록 하겠습니다!
