### ISSUE TITLE
[공통] useCase 모듈 고도화

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#22]
# 🤝 논의사항
useCase 모듈의 적용 로직을 조금 더 간결한 형태로 변경하는 방법은 제안드립니다.

<br/>

## 📝 상세 내용

현재 useCase 모듈은 아래와 같이 사용되고 있습니다.
##### UseCase 모듈
```dart
class GetChatRoomsUseCase
    extends BaseUseCase<String, Result<List<ChatRoomEntity>>> {
  GetChatRoomsUseCase(this._repository);

  final ChatRepository _repository;

  @override
  Future<Result<List<ChatRoomEntity>>> call(String request) {
    return _repository.getChatRoomList(request);
  }
}
```

##### UseCase 모듈을 참조하여 실행시키는 Provider
```dart

@riverpod  
class ChatList extends _$ChatList {  
  @override  
  FutureOr<List<ChatRoomEntity>> build() async {  
    final response = await getChatListUseCase('swift');  // <-- 1. useCase을 실행
    return response.fold(    // < -- 2. useCase를 응답값을 기반으로 에러핸들링 
      onSuccess: (chatList) {  
        return chatList;  
      },  
      onFailure: (e) {  
        log(e.toString());  
        throw e;  
      },  
    );  
  }
....
}
```

useCase 모듈을 참조하여 실행시키는 Riverpod의 Provider코드를 보면 useCase을 실행하는 코드와 useCase 응답값을 기반으로 에러핸들링을 하는 코드가 분리되어 있습니다.

문제가 있는 코드는 아니지만 조금 더 간결하게 구문을 적기 위해, usecase 실행하는 코드와 useCase 응답값을 기반으로 에러 핸들링을 하는 로직 을 병합하는 형태로 useCase 모듈을 구성해봐도 좋을 것 같다는 생각이 듭니다.

아직 구체적인 코드는 생각해보지 않았지만 아래와 같이 변경이 될 수 있을 것 같습니다.

```dart
@riverpod  
class ChatList extends _$ChatList {  
  @override  
  FutureOr<List<ChatRoomEntity>> build() async {  
	 return getChatListUseCase.call(
	   params: 'swift',
	   onSuccess : (chatList) => chatList;
	   onFailure : (error) {
	     log(e.toString());
	     throw e;
	   }
	 )
....
}
```

<br/>

## 🚀 기대 효과
- useCase 실행 구문을 간결하게 변경

<br/>

## 👷 참가자
@suneogkwon , @Xim-ya 

<br/>

## 💬 기타
- Flutter Meetup Songdo 23의 발표 내용을 참고했습니다.
  [상태관리 올바르게 쓰기](https://www.youtube.com/watch?v=XsbKfvznouA&list=LL&index=1)

<br/>

**Comment by suneogkwon** [comment]
프로젝트 진행하면서 느끼는 점이
1. use case에서 에러핸들링을 하고 또 provider로 Result를 넘겨줘야할까? 
2. riverpod에서 제공하는 asyncError 클래스와 listen 등으로 throw가 발생한 경우를 잡을 수 있는데 Result를 받아서 한번 더 처리할 필요가 있나?
3. 어차피 error는 처리를 위해 provider까지 내려오는데 공통된 작업(로그 기록 등)은 providerLogger에서 처리해도 되지않을까? 

제안해주신 정말 괜찮은 방법인 것 같습니다만 먼저 use case와 provider에서의 에러핸들링의 의의를 먼저 생각해봐야할 것 같아요.

**Comment by Xim-ya** [comment]
언급하신 항목에 대한 답변입니다!

> 1. use case에서 에러핸들링을 하고 또 provider로 Result를 넘겨줘야할까?

정확히는 useCase에서 에러핸들링을 한다기 보다는 성공 실패 경우를 이벤트를 처리하는 콜백함수를 provider를 넘겨주고 있습니다!
실패 경우에 간단히 로그만 찍어서 보여줄 수 있지만 상황에 따라서 snackBar 또는 dialog를 보여주는 경우가 있기 때문에 context를 참조할 수 있는 presentation layer 즉 provider에 전달하는게 필요하다고 생각합니다.

> 2. riverpod에서 제공하는 asyncError 클래스와 listen 등으로 throw가 발생한 경우를 잡을 수 있는데 Result를 받아서 한번 더 처리할 필요가 있나?

첫 번째 답변과 비슷한데, 성공 실패 할 경우 추가적인 위젯(snackbar or dialog)을 화면을 보여주기 위해서 Result 콜백 함수를 provider에서 실행시킬 필요가 있다고 생각합니다.

>3. 어차피 error는 처리를 위해 provider까지 내려오는데 공통된 작업(로그 기록 등)은 providerLogger에서 처리해도 되지않을까?

실패에 대한 로그 처리를 providerLogger에서 일관적으로 관리한다면 별도의 log 메소드는 필요없을 것 같습니다!

<hr/>

사실 제가 useCase레이어 도입을 제안드렸지만, 프로젝트를 진행하면서 useCase 레이어가 필요한지 의문이 듭니다.
처음에는 유닛 테스트에 이점이 있을 것 같다고 생각했는데, riverpod 을 사용해보니 개별 provider를 테스트하는게 훨씬 더 괜찮을 것 같고요..
조심스럽게 useCase 레이어를 없애는 방향을 제안드려 봅니다...

**Comment by suneogkwon** [comment]
>정확히는 useCase에서 에러핸들링을 한다기 보다는 성공 실패 경우를 이벤트를 처리하는 콜백함수를 provider를 넘겨주고 있습니다!
실패 경우에 간단히 로그만 찍어서 보여줄 수 있지만 상황에 따라서 snackBar 또는 dialog를 보여주는 경우가 있기 때문에 context를 참조할 수 있는 presentation layer 즉 provider에 전달하는게 필요하다고 생각합니다.

이해했습니다. 그러면 현재 repository 레이어에서 Result로 응답을 해주고 있는데 use case에서는 단순 전달만하는 역할로 이해해도 될까요? 말씀하신 이벤트를 처리하는 콜백함수 생성을 repository가 해주고 있고 에러 처리를 위한 context 참조는 provider가 하고있으니까요!

>첫 번째 답변과 비슷한데, 성공 실패 할 경우 추가적인 위젯(snackbar or dialog)을 화면을 보여주기 위해서 Result 콜백 함수를 provider에서 실행시킬 필요가 있다고 생각합니다.

면접주제 조회를 예로들면 현재 코드는
```dart
  final topicResult =await getTopicsUseCase();
  return topicResult.fold(
    onSuccess: (value) => value,
    onFailure: (e) {
      log('$e');

      throw e;
    },
  );
```
위 처럼 `onFailue`를 작성자가 처리하고 UI 상 error처리를 위해 다시 `throw e`를 하고 있습니다.
이를 `ref.listenSelf`를 사용한다면

```dart
ref.listenSelf(
    (_, __) {},
    onError: (error, stackTrace) {
      log('$error');
    },
  );

  final topic = await getTopicsUseCase();
  return topic;
```
이와 같이 변경할 수 잇습니다.

또한, extension을 사용하면 
```dart

extension on Ref {
  void onError(void Function(Object error, StackTrace stackTrace)? onError) {
    listenSelf(
      (previous, next) {},
      onError: onError,
    );
  }
}

  ref.onError(
    (error, stackTrace) {
      log('$error');
    },
  );

  final topic = await getTopicsUseCase();
  return topic;
```
좀 더 간결히 작성할 수 있습니다.

>실패에 대한 로그 처리를 providerLogger에서 일관적으로 관리한다면 별도의 log 메소드는 필요없을 것 같습니다!

동의합니다!

>사실 제가 useCase레이어 도입을 제안드렸지만, 프로젝트를 진행하면서 useCase 레이어가 필요한지 의문이 듭니다.
처음에는 유닛 테스트에 이점이 있을 것 같다고 생각했는데, riverpod 을 사용해보니 개별 provider를 테스트하는게 훨씬 더 괜찮을 것 같고요..
조심스럽게 useCase 레이어를 없애는 방향을 제안드려 봅니다...

그럼 출시 하고 한번 고려해보죠! 저도 use case가 득보단 실인 것 같아 고민하고 있었거든요 DI 주입할게 너무 많아져서,,

**Comment by Xim-ya** [comment]
1. UseCase의 역할 및 개선 방안
> 이해했습니다. 그러면 현재 repository 레이어에서 Result로 응답을 해주고 있는데 use case에서는 단순 전달만하는 역할로 이해해도 될까요?

네 상황에 따라 다른데, 만약 간단한 데이터 호출 동작이라면 useCase에서는 단순히 전달하는 역할 수행합니다.
다만 조금 더 복잡한 비즈니스 로직을 고려해야되는 경우 관련 로직을 useCase에서 관리하는 경우가 있습니다. (get_answer_feedback_use_case.dart 참고).

현재 작성된 useCase들의 대부분은 단순히 repository의 응답만을 전달하는 경우가 많기 때문에 useCase 레이어를 생략해도 되지 않을까 라는 생각을 하고 있습니다.

대신 단순 응답을 전달하는 useCase가 아니라 비즈니스 로직을 처리하는 useCase의 경우, 해당 로직을 provider에서 처리하도록 변경하고, 관련 로직들에 대한 정보를 담고 있는 추상화 모듈을 기존 useCase 대신에 적용하는건 어떤가 싶네요. 

설명이 조금 복잡한데 코드로 표현하면 아래와 같습니다.

```dart
@Riverpod(dependencies: [chatPageRouteArg])  
class ChatHistory extends _$ChatHistory implements GetFeedBackUseCase {  // <- 추상화된 useCase 모듈을 implement함 (인터페이스 성격을 가지고 잇음)
	
  @override  
  FutureOr<List<MessageEntity>> build() async {  
    ref.onDispose(() {  
      ref.invalidate(totalQnaListProvider);  
    });


// useCase 메소드들을 오버라이드.
@override
Future<void> addUserChatResponse({required String message}) async {

...
}


....
}
```


<br/>

2. riverpod을 활용한 에러핸들링
```dart
extension on Ref {
  void onError(void Function(Object error, StackTrace stackTrace)? onError) {
    listenSelf(
      (previous, next) {},
      onError: onError,
    );
  }
}

  ref.onError(
    (error, stackTrace) {
      log('$error');
    },
  );

  final topic = await getTopicsUseCase();
  return topic;
```
오 이렇게 접근 할 수 도 있겠네요.  
항상 느끼는건데 riverpod에 대한 이해도가 진짜 높으시네요.. 진지하게 riverpod 사용 사례 관련해서 시리즈로 포스팅글을 작성해보셔도 좋을 것 같습니다. 

암튼 각설하고, 이 방법도 괜찮지만 저는 기존처럼 result로 성공 실패에 구문을 적는게 조금 더 직관적으로 보입니다. 성공과 실패에 대한 로직이 한 메소드(구문)으로 처리되는게 개인적으로 조금 더 간결해보입니다.

그리고 만약 나중에 riverpod에서 다른 상태 관리 라이브러리로 마이그레이션 한다고 했을 때도 위 제안주신 방식보다 기존 방식을 유지하는게 유리해 보입니다. 저희가 riverpod을 사용하지 않고 get_it을 이용해 di로직을 구현한 이유와 비슷하게요.

마지막으로 Result타입으로 선언된 객체들을 항상 성공과 실패에 대한 예외처리 구문을 고려해야 실제 객체 데이터에 접근할 수 있는 방식이기 때문에(물론 getOrThrow를 쓰면 생략 가능) , 작업자가 예외처리 로직을 적지 않는 실수로 방지해 준다고도 생각합니다!

**Comment by Xim-ya** [comment]
📝 

- 기존 useCase 모듈 유지 및 Result를 활용한 에러 핸들링 방안 유지
- 앱 출시 이후 useCase 유지 여부 및 고도화 방안에 논의해도 늦지않다고 판단.
