### ISSUE TITLE
[채팅 면접] 채팅 면접 프로세스 오류 

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#28]
# 🐛 버그 보고
채팅 면접 섹션에서 아래와 같은 오류 및 개선해야되는 부분이 있어서 공유드립니다.

- 마지막 면접 질문을 답하고 면접이 종료되었다는 메세지를 보여주지 않고 있음.
- 현재 진행중인 채팅을 임시중단하고 '면접실 페이지'로 이동하였을 때 채팅 데이터가 동기화되지 않음.

<br/>

#### 1. 마지막 면접 질문을 답하고 면접이 종료되었다는 메세지를 보여주지 않고 있음.

![Simulator Screenshot - iPhone 12 mini - 2023-12-28 at 13 15 46](https://github.com/MakeFrog/TechTalk/assets/75591730/59fdfe71-bdec-4cb3-94b5-0672b2e701d6)

#### 2 .  현재 진행중인 채팅을 임시중단하고 '면접실 페이지'로 이동하였을 때 채팅 데이터가 동기화되지 않음.

https://github.com/MakeFrog/TechTalk/assets/75591730/b3c562cc-af68-4378-9a88-97a0358cf632

(동영상)

<br/>

## 🤔 기대 동작

1. 설정된 인터뷰 질문이 개수가 없을 때 면접이 종료되었다는 'Guide' 채팅 메세지가 노출되어야 함.
2. 현재 진행중인 면접을 종료하고 면접실 페이지로 이동하였을 때 기존 채팅 면접 데이터가 동기화 되어야 함.

<br/>

## 👷 담당자
- 미정

<br/>

## 🌍 환경

Framework • revision 2e9cb0aa71 (2 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
Device : iphone 12 (17.2)

**Comment by suneogkwon** [comment]
오류 수정 완료 0c04c249461f00b031ec2f8945e43c6c8d363969
