### ISSUE TITLE
[홈] 주제별 면접 카드 섹션 로직 개선

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#29]
# 🐛 버그 보고
주제별 면접 카드 섹션에서 개선해야할 로직이 있어서 공유드립니다!

<br/>

## 💻 재현 또는 코드 샘플
![er](https://github.com/MakeFrog/TechTalk/assets/75591730/686b2e62-d2c7-4325-9f65-1fc5b156c2e1)

<br/>

## 😯 현재 동작
- 주제별 면접 카드에서 유저 데이터베이스에 저장되어 있는 면접 주제와 관련 없는 topic 리스트가 보여지고 있음
- 면접 보기를 클릭 했을 때 항상 '면접실 페이지'로 이동하고 있음. 
  

<br/>

## 🤔 기대 동작
 -  홈 페이지의 주제별 면접 카드에서 보여지는 면접 주제 리스트는 유저 데이터베이스 설정되어 있는 면접 주제 리스트만 보여주어야 함.
 - '면접 보기' 버튼을 클릭했을 때, 해당 면접 주제와 관련된 진행중이거나 종료된 채팅방 목록 데이터가 없다면 문제 개수를 선택하는 페이지로 이동해야됨.
 
<br/>

##👷 담당자

미정

<br/>

## 🌍 환경

- Framework • revision 2e9cb0aa71 (2 weeks ago) • 2023-12-11 14:35:13 -0700
- Engine • revision 54a7145303
- Tools • Dart 3.2.3 • DevTools 2.28.4
- Device : iphone 12 (17.2)

**Comment by suneogkwon** [comment]
> '면접 보기' 버튼을 클릭했을 때, 해당 면접 주제와 관련된 진행중이거나 종료된 채팅방 목록 데이터가 없다면 문제 개수를 선택하는 페이지로 이동해야됨.

이 사항은 고려하지 못했네요. 적용해놓겠습니다.

**Comment by suneogkwon** [comment]
오류 수정 완료
* 유저가 선택한 면접 주제만 나오도록 수정 3e6a3575b01597d158a73beb0bd543f6baca253b
* 진행중인 면접이 없다면 면접 시작하기 화면으로 이동 9de9931b8cfda5249580ba0c623dad043ab0b39b
