### ISSUE TITLE
[공통] Riverpod provider 사용 범위 구조화

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#31]
# 🤝 논의사항
riveprod 의 provider는 전역(top-level)으로 선언되기 때문에 특정 섹션에 어떤 provider가 사용되고 있는지 파악하는데 어려움이 있습니다.

> Class 또는 타입으로 매핑되어 사용범위를 명확히 추적할 수 있는 다른 상태 관리 라이브러리와 확연한 차이가 있습니다. 

결과적으로 특정 섹션에 어떤 provider가 사용되지 파악하기 힘들 경우 유지보수와 테스트 코드를 작성하기 힘든 구조가 됩니다. 

이 문제를 해결하기 위해 mixin class를 이용하여 provider의 state 및 event를 구조화 시키는 방법을 제안드립니다!
## ❗NOTE
해당 솔루션은 기존에 **순억님이 제안해주신 mixin event** 모듈과 더불어 provider의 state이  관리되고 있는 mixin state 모듈을 함께 사용하는 방법입니다. 
#### (순억님이 제시해주신 솔루션에 큰 영감을 받았습니다)

이전에 피드백주신 3가지 이슈 (cache, auto dispose, watch side effect) 내용 관련해서 테스트 진행했고 문제가 없었습니다.

<br/>

#### Event Mixin (기존과 동일)
```dart
mixin class ProfileSettingEvent {  
  ///  
  /// 프로필 이미지 탭 되었을 때  
  ///  
  void onProfileImgTapped(WidgetRef ref) async {  
    await EasyLoading.show();  
    unawaited(  
      ref  
          .read(pickedProfileImgProvider.notifier)  
          .pickImageFile()  
          .whenComplete(EasyLoading.dismiss),  
    );  
  }  
  
  ///  
  /// 닉네임이 입력되었을 때  
  ///  
  void onNicknameChanged(WidgetRef ref, {required String? input}) {  
    return ref.read(nicknameInputProvider.notifier).onInputChanged(input);  
  }

....
}
```
- 특정 페이지 영역에서 사용되는 provider의 event 로직들을 관리하는 mixin class 모듈

#### State Mixin
```dart
mixin class ProfileSettingState {  
  ///  
  /// 이미지 파일  
  ///  
  File? pickedImgFile(WidgetRef ref) => ref.watch(pickedProfileImgProvider);  
  
  ///  
  /// 유저 정보  
  ///  
  UserDataEntity user(WidgetRef ref) => ref.watch(userDataProvider).value!;

...
}
```
- 특정 페이지 영역에서 사용되는 provider의 state 상태값들을 관리하는 mixin class 모듈
#### Page
```dart
class ProfileSettingPage extends BasePage with ProfileSettingState, ProfileSettingEvent {

@override
build(ref, context) {

// SAMPLE
final pickedImage =  pickedImgFile(ref); // state
final Voidcallback = onProfileImgTapped(ref); // event

...return
  }
}
```
- 앞서 생성된 state event mixin 모듈들은 페이지 부모 및 자식 위젯에 mixin되어 위젯에 event 및 state 값을 전달합니다.

#### TestCode

```dart
void main() {  
  final homeEvent = HomeEventTest();  
  final homeState = HomeStateTest();  
  
  test('Add todo', () {  
    final container = createContainer();  
    const String todoDescription = 'Write Riverpod Test Code';  
    homeEvent.onTodoSubmitted(container,  
        textEditingController: TextEditingController(), value: todoDescription);  
  
    expect(  
        homeState.filteredTodos(container).last.description, todoDescription);  
  });  
  
  test('Remove todo', () {  
    final container = createContainer();  
    final selectedTodo = homeState.filteredTodos(container).last;  
    homeEvent.onTodoDismissed(container, selectedTodo: selectedTodo);  
  
    expect(  
        homeState  
            .filteredTodos(container)  
            .firstWhereOrNull((e) => e.id == selectedTodo.id),  
        null);  
  });
  
}
```
- 각 state 및 event 로직들을 인스턴스화하여 유닛 테스트 코드를 아주 쉽게 작성할 수 있습니다.
- 또한 provider의 사용영역이 구조화되어 있고 evet mixin 모듈을 통해 이벤트 로직들을 추적하기 용이하기 때문에 테스트 범위를 산정할 때도 도움이 될 것 같습니다.
- 또한 이벤트 메소드들이 한 곳에 구조화되어 있기 때문에 테스트 시나리오별로 유닛 테스트 코드를 작성하기 용이해집니다.

<br/>

## 🚀 기대 효과

- 유지보수 향상 : provider 사용 범위 구조화여 provider관련 로직을 쉽게 추적 및 파악할 수 있음
- 유닛 테스트 용이 : state 및 event 로직들을 인스턴스화하여 유닛 테스트 코드를 아주 쉽고 빠르게 작성할 수 있음.

<br/>

## 👷 참가자
@suneogkwon  @Xim-ya 

<br/>

## 💬 기타

해당 이슈 관련해서 다음 정기회의 때 도입 여부를 이야기해보고 싶습니다.
만약 도입이 된다면 현재 작성된 코드를 전환하는데 리소스가 많이 들어가기 때문에 추후 리팩토링 하는 방향으로 진행하면 좋을 것 같아요.

**Comment by suneogkwon** [comment]
전역 상태관리를 사용함으로써 특정 페이지에서 사용되는 상태를 찾기 힘든 점에 저도 공감합니다.
제안해주신 방법이 앞서말한 애로사항을 해결해주는 획기적인 방법인 것 같습니다.

**Comment by Xim-ya** [comment]
ㅋㅋㅋㅋㅋㅋ 순억님이 기존 제안해 주신 **event mixin module**에서 state module만 추가된 겁니다.

이전에 말씀드린 것 처럼 지금은 riverpod을 제일 선호하는 편인데,
제안해주신 event mixin 모듈을 활용해서 provider 사용 범위를 구조화시키는 방법을 몰랐으면
여전히 provider나 bloc을 더 선해했을 것 같다는 생각이 듭니다.


> 지금부터 새롭게 작업들어가는 영역만 state mixin 모듈을 적용하겠습니다!
