### ISSUE TITLE
[로그인] 오류 수정 및 기능 보완

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#33]
# 🏷️ 요약
로그인 및 스플래시 섹션에서 빌셍하는 오류와 기능을 수정 보완합니다.

<br/>

## 📄 명세
- [x] 소셜 로그인 오류 수정 (errorcode : 1002, 1001)
- [x] 유저 `lastLoginDate` 필드값 추가
- [x] 최초 로그인시 lastLoginDate 필드값 업데이트
- [x] 이미 로그인한 유저는 splash 단계에서 lastLoginDate 필드값 업데이트

<br/>

## 👷 작업자
미정

<br/>

## 💬 기타
없음

**Comment by suneogkwon** [comment]
@suneogkwon 배정
