### ISSUE TITLE
[온보딩]  오류 수정 및 기능 보완 

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#34]
# 🏷️ 요약
온보딩 섹션에서 빌셍하는 오류와 기능을 수정 보완합니다.

<br/>

## 📄 명세
- [x] 닉네임 유효성 검사 로직 추가 (닉네임 글자 수 제한 2글자 이상 10글자 이내)
- [x] 닉네임 충족 조건 요건 로직 오류 수정 (하단 고정 버튼 활성화 여부)
- [x] 온보딩 단계에서 유저 정보 업데이트 시점 변경 (모든 단계를 마무리한 후 유저 정보를 업데이트) 

<br/>

## 👷 작업자
@Xim-ya 

<br/>

## 💬 기타
해당 이슈는 제가 마이페이지 섹션 내용 수정하면서 함께 수정하겠습니다!

**Comment by suneogkwon** [comment]
@Xim-ya 

> 닉네임 충족 조건 요건 로직 오류 수정 (하단 고정 버튼 활성화 여부)
 온보딩 단계에서 유저 정보 업데이트 시점 변경 (모든 단계를 마무리한 후 유저 정보를 업데이트)

해당 이슈는 #45 PR에 수정되어 올라갔습니다. 확인 부탁드려요

**Comment by Xim-ya** [comment]
확인했습니다!
