### ISSUE TITLE
[채팅 인터뷰] 실전형 면접 기능 추가 대응 및 기타 이슈 수정

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#35]
# 🏷️ 요약
실전형 면접 기능을 추가합니다.  

<br/>

#### 홈
- [x] 홈 버튼에서 '실전형 카드'를 클릭하면 면접 주제 선택 화면으로 이동
- [x] 실전형 면접 채팅방 목록을 2번 호출하는 이슈
- [x] 실전 면접 중복 라우팅 이슈 수정

#### 면집실 (채팅 목록)
- [ ] 실전면접 채팅방 목록 페이지 UI 추가 (면접 주제 리스트가 해당하는 채팅방 UI에 보여지는 형태) 
- [x] 면접 주제 선택 페이지 UI 개선 
- [x] 채팅방 데이터 초기화 시점 변경

#### 면접 주제 선택
- [x] 기존 면접 주제 선택 페이지와 다르게 다중선택이 가능해야됨 (최소 1개, 최대 3개) 
- [x] 3개의 면접 주제가 선택된 상태에서 유저가 다른 면접 주제를 선택할 경우 최대 3개만 선택가능하다는 snackbar 팝업창을 노출.
- [x] 2개 이상의 면접 주제를 클릭했을 경우에만 하단 '다음' 버튼 활성화
- [x] 스크롤 레이아웃 변경 (디자인 참고)
- [ ] 실전형 면접 주제 선택 페이지 서브 가이드 텍스트 추가

##### 채팅 인터뷰
- [x] 기존 채팅 Qna 목록을 가져올 때 실제로 진행된 면접 질문 순서와 일치하지 않는 이슈 수정
- [ ] chat gpt promt 로직 고도화
- [x] 실전 면접에서 최초 랜던함 qna 목록을 가져올 때 유저가 선택한 질문개수만큼 문제를 가져오지 못하는 오류
- [x ] 초기 채팅방 입장시 채팅 목록을 불필요하게 불러오는 로직 수정
- [x] 선택된 면접 주제들이 골고루 질문으로 제시 되어함. ex) 3개의 면접 주제,  면집 질문 3개 -> 각 면접 주제마다 하나씩 물어봐야함.
- [x] 선택된 면접 주제들이 골고루 제시 되어야하지만 면접 주제 순서별로 질문이 제시되면 안됨. 
ex) flutter -> flutter -> swift -> swift -> swift (x) / flutter -> swift -> swift -> flutter (o) 

<br/>

## 👷 작업자
@Xim-ya 

<br/>

## 💬 기타
없음

**Comment by suneogkwon** [comment]
@suneogkwon 배정

**Comment by suneogkwon** [comment]
@Xim-ya 

실전형 면접 기능 추가에 따라 기존 기능에 변화가 있는데 제가 임의로 진행해두긴했는데 시간날때 논의해보면 좋을 것 같습니다.
* ChatRoomEntity에 실전형, 주제별 타입 필드를 추가할지, Entity를 분리할지 논의
  * 현 : ChatRoomEntity에 InterviewType이라는 enum을 추가, 다중면접주제를 받아야하기에 ChatRoomEntity.topic을 List 형식으로 변경
* 라우트를 추가할지, 기존 라우트에 타입을 추가로 전달할지 논의
  * 현 : 타입 값이 필요한 곳(면접방리스트 페이지, 면접 주제 선택 페이지, 면접 페이지)에 type 파라미터 전달

**Comment by Xim-ya** [comment]
#### 1. ChatRoomEntity 관련
현재 구현해주신 것 처럼, topicEntity를 List로 지정해주면 될 것 같습니다!

#### 2. 라우트를 추가할지, 기존 라우트에 타입을 추가로 전달할지 논의
라우트를 추가한다는건 새로운 페이지를 만든다는 것 인가요? 개인적으로 현재 구현해주신 것 처럼 type 파라미터를 조건별로 전달해도 충분할 것 같습니다!

**Comment by Xim-ya** [comment]
@suneogkwon 

실전형 면접 기능 추가로 인한 새로운 UI 및 관련 로직이 필요한 task를 추가해두었습니다.
추가된 디자인은 피그마에서 확인해보실 수 있어요!
> 작업 들어가시기 전에 미리 확인하고 디자인을 제공드렸어야 했는데 죄송합니다 😭

**Comment by Xim-ya** [comment]
https://github.com/MakeFrog/TechTalk/pull/56 일부 이슈 task 수정.

https://github.com/MakeFrog/TechTalk/issues/57 해당 이슈를 닫고 나머지 task는 새로운 이슈에서 관리.
