### ISSUE TITLE
[홈] 기능 보완

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#36]
# 🏷️ 요약
홈 섹션에서 일부 기능을 보완합니다.

<br/>

## 📄 명세

- [x] 주제별 면접 카드에서 조건에 따라 면접 주제 항목을 노출. (한번이라도 면접을 본 주제이거나 관심 면접 데이터에 포함된 경우)
- [x] 유저가 새로운 면접 주제에 대해 채팅방을 생성할 경우 홈 섹션의 주제별 면접 카드에서 데이터가 동기화 되어야 함.
- [x] 한번이라도 면접을 진행한 기록 존재 여부에 따라 가이드 텍스트를 조건 별로 노출 해야함.
- [x] 주제별 면접 카드에서 디자인과 상이한 UI 수정 (카드 하단 여백) 

<br/>

## 👷 작업자
미정

<br/>

## 💬 기타
없음

**Comment by suneogkwon** [comment]
@suneogkwon 배정
