### ISSUE TITLE
[채팅 인터뷰] 기능 보완

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#37]
# 🏷️ 요약
채팅 섹션에서 추가 기능을 보완합니다.

<br/>

## 📄 명세

- [x] 유저가 채팅을 보낼 때 이전 면접관의 채팅이 중복되어 보여지는 이슈
- [x] 최초 면접 진행시 보여지는 인사말 (guide text)를 랜덤하게 보여줍니다 (2~3개)
- [x] 면접이 종료되었다면 채팅을 벗어날 때 보여지는 팝업 다이어로그 보여주지 않아야 함.
- [x] 면접실 페이지에서 해당 면접 주제에 해당하는 채팅방이 20개가 넘어가면 가장 마지막 채팅방이 삭제 되어야 함.
- [x] ai 피드백 오류 리포트 로직 추가

<br/>

## 👷 작업자
@suneogkwon  @Xim-ya 

<br/>

## 💬 기타
없음

**Comment by suneogkwon** [comment]
@suneogkwon 배정
