### ISSUE TITLE
[학습] 기능을 추가 및 보완

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#38]
# 🏷️ 요약
학습 페이지에서 일부 기능을 추가 및 보완합니다.

<br/>

## 📄 명세

- [x] 전체문항 페이지로 이동할 때 현재 선택된 문항이 있는 아이템으로 스크롤  포지션이 이동 되어야 함.  
- [x] 전체문항 페이지에서 현재 선택된 문항이 activate된 UI 로직 추가.

<br/>

## 👷 작업자
미정

<br/>

## 💬 기타
없음

**Comment by suneogkwon** [comment]
@suneogkwon 배정
