### ISSUE TITLE
[로그인] SNS 로그인 프로세스를 중단하면 화면이 멈추는 버그

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#5]
# 🐛 버그 보고
SNS 로그인 프로세스를 중단했을 때 화면 멈추는 버그가 발생합니다.

<br/>

## 💻 재현 또는 코드 샘플

https://github.com/MakeFrog/TechTalk/assets/75591730/bc9186fa-f1de-49b7-980f-37654c61fc2a

<br/>

## 🤔 기대 동작

https://github.com/MakeFrog/TechTalk/assets/75591730/7f4f491f-5473-4614-a2c3-88d3bb213e9f
(plotz 앱)

유저가 SNS 로그인 프로세스를 도중에 중단하면  유저에게 로그인 프로세스가 중단되었다는 `팝업 메세지`를 보여주어야 함.

<br/>

## 😯 현재 동작 
SNS 로그인 프로세스를 도중에 중단하면 화면 전체 로딩(EasyLoading) 상태가 진행되면서 앱을 작동할 수 없는 상태가 됩니다.

<br/>

## 💁 오류 원인 분석 및 해결책 제시
FirebaseAuthentication 관련 코드에서 `try catch` 사용하여 예외처리를 할 수 있어야 합니다.

## 🌍 환경
운영 체제 및 장치:  [iOS16.2, iPhone 12 mini]

**Comment by suneogkwon** [comment]
수정했습니다. [fix: 소셜 로그인 중단 시 로딩 인디케이터 삭제되지 않는 이슈 수정](https://github.com/MakeFrog/TechTalk/commit/a596a8b43d870ccb9065c2a27c770a1a4edcc005)

**Comment by Xim-ya** [comment]
넵 수고하셨습니다!
