### ISSUE TITLE
[학습] cache layer 구축

### ISSUE THREAD

**Issue by Xim-ya** [MakeFrog/TechTalk#9]
# 🚀 기능
학습탭에서 선택된 학습 주제의 질문과 모범답변 데이터를 불러올 때 데이터 업데이트 여부에 따라 로컬에 캐싱된 데이터를 활용합니다. 이를 통해 서버 통신을 최소화하여 애플리케이션의 성능을 향상시킬 수 있습니다.

## 📸 재현 이미지 또는 코드 샘플

<img width="1646" alt="arang" src="https://github.com/MakeFrog/TechTalk/assets/75591730/be6edd63-6138-4700-b603-941197ee38b1">
학습탭에서 문답(질문과 모범답변) 데이터를 호출할 때 아래 2가지 조건을 만족하면 서버에서 데이터를 가져오지 않고 내부에 캐싱된 데이터를 가져옵니다.

- 로컬에 캐싱된 데이터가 존재해야 합니다.
- 로컬에 캐싱된 데이터가 존재하고 해당 데이터가 최신 상태여야 합니다.

> 데이터의 최신화 여부는 서버와 로컬의 데이터 키 값을 대조하여 확인합니다.

## 📄 기능 명세
- 서버와 통신하여 선택된 학습 주제의 키 값을 요청합니다.
- 로컬에 저장된 선택된 학습 주제의 키 값을 확인합니다.
- 서버의 키 값과 로컬의 키 값을 대조하여 데이터의 최신화 여부를 판단합니다.
- 데이터의 최신화가 필요한 경우, 서버에서 문답 리스트와 키 데이터를 가져와 로컬 데이터를 최신화합니다.
- 만약 로컬에 선택된 학습 주제에 관련한 캐싱 데이터가 없다면, 서버에서 문답 리스트와 키 값을 가져와 로컬에 캐싱 데이터를 저장합니다.

## 👷 작업자
@suneogkwon 

## 💬 기타
만약 외부 Local Storage 패키지를 사용한다면 아래의 기준을 고려해보셔도 좋을 것 같아요!

- 로컬 데이터베이스에 데이터를 효율적으로 저장할 수 있는지 
- 로컬 데이터베이스에서 원하는 데이터를 쉽게 검색하고 필터링할 수 있는지

**Comment by suneogkwon** [comment]
캐시를 저장해 불필요한 트래픽 낭비를 줄이는 건 좋은 생각인 것 같습니다. 말씀해주신 키로 최신 데이터인지 비교하는 방법도 좋은 방법이라 생각합니다. 

협의한 방향으로 개발 진행했으며 따로 로컬 스토리지는 사용하지 않고 firestore에서 제공해주는 로컬 캐시를 사용했습니다.

```dart
/// lib/features/study/repositories/study_repository_impl.dart

@override
  Future<Result<StudyQuestionListEntity>> getQuestionList(String techId) async {
    StudyQuestionListModel questionsModel;

    StudyQuestionListModel? cacheQuestionsModel =
        await _studyLocalDataSource.getQuestionList(techId);

    if (cacheQuestionsModel != null) {
      final lastUpdateDate =
          await _studyRemoteDataSource.getLastQuestionsUpdateDate(techId);
      if (lastUpdateDate.compareTo(cacheQuestionsModel.updateDate) == 0) {
        questionsModel = cacheQuestionsModel;
      } else {
        questionsModel = await _studyRemoteDataSource.getQuestionList(techId);
      }
    } else {
      questionsModel = await _studyRemoteDataSource.getQuestionList(techId);
    }

    return Result.success(
      StudyQuestionListEntity.fromModel(questionsModel),
    );
  }
```
`usecase`로부터 호출되는 repository 매소드입니다. 
플로우는
1. 캐시된 데이터를 가져온다.
2. 캐시 데이터가 존재하지 않는다면 5번으로 이동한다.
3. 캐시된 데이터가 존재한다면 원격에서 데이터 키를 가져온다.
4. 캐시된 데이터 키와 원격 데이터 키를 비교해 같다면 캐시데이터를 반환하며 매소드를 종료한다. 다르다면 5번으로 이동한다.
5. 원격에서 데이터를 가져와 캐시 저장 후 반환한다.

```dart
/// lib/features/study/data/local/study_local_data_source_impl.dart

@override
  Future<StudyQuestionListModel?> getQuestionList(String techId) async {
    final docRef =
        _firestore.collection(FirestoreCollection.study.name).doc(techId);
    final docSnapshot = await docRef.get(
      const GetOptions(
        source: Source.cache,
      ),
    );

    if (!docSnapshot.exists) {
      return null;
    }

    return StudyQuestionListModel.fromFirestore(docSnapshot);
  }
```
`local data source`에서 캐시된 학습 리스트를 조회하는 매소드입니다.
firestore 자체 로컬 캐시 기능을 사용했습니다. `GetOptions`에서 제공하는 캐시만 조회할지, 원격만 조회할지 등의 옵션을 사용했습니다.
데이터가 존재한다면 데이터를, 아니라면 null을 반환합니다.

```dart
/// lib/features/study/data/remote/study_remote_data_source_impl.dart

  @override
  Future<DateTime> getLastQuestionsUpdateDate(String techId) async {
    final docRef =
        _firestore.collection(FirestoreCollection.study.name).doc(techId);
    final docSnapshot = await docRef.get();
    final updateDate = docSnapshot.get('update_date') as Timestamp;

    return updateDate.toDate();
  }
```
firestore 서버에서 학습 목록의 데이터 키를 가져오는 매소드입니다. 로컬 데이터 키와 비교 시 사용할 키를 조회하는 용도로 사용합니다.
키는 서버에 `update_date`라는 필드로 저장되어있으며, 타입은 `Timestamp`를 사용하였습니다. key 타입은 임의로 정했으며 협의 후 변경해도 괜찮을 것 같습니다.
